### PR TITLE
Ssl

### PR DESCRIPTION
**Pull request by Lyr3x**
added ssl and certificates :laughing:

### CODE REVIEW

**Comment by Nesurion** [comment]
I'll test this tomorrow or so and get back to you

**Comment by Lyr3x** [comment]
+

Nesurion <notifications@github.com> schrieb am Fr., 17. Juli 2015 00:06:

**Comment by Nesurion** [comment]
redirecting http request to https would be awesome. Maybe this could help https://github.com/tobmatth/rack-ssl-enforcer

**Comment by Lyr3x** [comment]
ill test it

Nesurion <notifications@github.com> schrieb am Fr., 17. Juli 2015 um
13:47 Uhr:

**Comment by Nesurion** [comment]
nevermind will go without the redirect for now. Create a new issue if this becomes a problem

**Pull request closed without merging**
